# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3a68d4815bc2448480e01a70fe116e186555c6dbd5ec3507971dc9a5831721f5de4acc7c48b999deb45bca77a99ee9a2570b02d924433489fdf1d0fe4812845f

test:
  secret_key_base: dc8b902c562a431452152c3b972650c020ea4010288d302a6790981052801ca120ce5b30f4988c1436dd4889bec54d2d283123955082a8319a4fa35d04b27478

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
